name: drone-methane-venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - jupyter
  - notebook
  - conda-forge::mlxtend
  - pydotplus
  - markdown
prefix: /opt/anaconda3/envs/drone-methane-venv
