name: drone-methane-venv
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0
  - aom=3.12.1
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.1
  - contourpy=1.2.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gts=0.7.6
  - h11=0.16.0
  - harfbuzz=10.2.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.15.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.4
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libboost=1.88.0
  - libcurl=8.16.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtool=2.4.7
  - libunistring=1.3
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mlxtend=0.23.4
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.117
  - numexpr=2.10.1
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openjpeg=2.5.4
  - openssl=3.0.18
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.3.7
  - poppler=24.09.0
  - poppler-data=0.4.12
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycparser=2.23
  - pydotplus=2.0.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.25
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=72.1.0
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.51.0
  - stack_data=0.6.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /opt/anaconda3/envs/drone-methane-venv
